site: Mark Kazzaz's Personal Blog

url: https://kzbigboss.github.io/
baseurl: blogdevelopment

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  cars:
    output: true
    permalink: /cars/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      featured_image: /images/elements/header.jpeg
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "cars"
    values:
      layout: "page"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 6
paginate_path: "/blog/page:num/"
